import type { Metadata } from "next";
import { Geist, Geist_Mono, Roboto, Inter } from "next/font/google";
import "./globals.css";
import { cn } from "@/lib/utils";

const interHeading = Inter({ subsets: ["latin"], variable: "--font-heading" });

const roboto = Roboto({ subsets: ["latin"], variable: "--font-sans" });

export const metadata: Metadata = {
     title: "Create Next App",
     description: "Generated by create next app",
};

export default function RootLayout({
     children,
}: Readonly<{
     children: React.ReactNode;
}>) {
     return (
          <html
               lang="en"
               className={cn(
                    "h-full",
                    "antialiased",
                    roboto.variable,
                    interHeading.variable,
                    "font-sans",
               )}
          >
               <body className="min-h-full flex flex-col">{children}</body>
          </html>
     );
}
